# Welcome to Agency Jekyll Theme!

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Xpress Math 
email: mohcine.madkour@gmail.com
description: > # this means to ignore newlines until "author:"
  This Xpress Math 
author: Mohcine Madkour
keyword: xpressmath
baseurl: "/xpressmath" # the subpath of your site, e.g. /blog
url: "https://mohcinemadkour.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mohcinemadkour

# Build settings

markdown: kramdown

#theme: agency-jekyll-theme #The "agency-jekyll-theme" is not supported by GitHub Pages. 

gems:
  - jekyll-feed
exclude:
  - agency-jekyll-theme.gemspec
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
